[versions]
agp = "8.1.0"
kotlin = "1.9.0"
compose = "1.5.0"
hilt = "2.47"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.8.0" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }

lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.6.2" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.9.0" }

coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.7.3" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.1.0" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version = "2.4.0" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
